name: Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Actions орчинд Java болон Maven-ийг суулгах
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      # 2. Кодыг татаж авах
      - name: Checkout code
        uses: actions/checkout@v3

      # 3. Maven үйлдлийг гүйцэтгэх
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # 4. Тестүүдийг ажиллуулах
      - name: Run tests with Maven
        run: mvn test --no-transfer-progress

      # 5. Шинжилгээ хийх, кодын чанарыг шалгах (Optional, if you want code quality checks)
      - name: Check code quality with Maven
        run: mvn verify
